name: Try Log Secrets

on:
  workflow_dispatch:    
     

jobs:
  log:
    runs-on: ubuntu-latest

    environment: 
      name: Production
    steps:
      - name: Log the secret
        run: echo ${{ secrets.MY_SECRET}}
